# stdlib

# third party
import toolz as fp
import numpy as np
import scipy.cluster.hierarchy as clus


def z(embedding):
    """
    Retrieve a cluster hierarchy array

    Uses ``scipy.cluster.hierarchy.linkage`` and ``ward`` linkage

    Parameters
    ----------
    embeddings : numpy.ndarray or list[float]
        the embeddings to be clustered by
   
    """
    return clus.linkage(embedding, "ward")


def fetch(depth, links):
    """
    Returns the cluster number for each row of the original data

    Parameters
    ----------
    depth : float
        the distance/depth paramater for the optimus cut off

    links : numpy.ndarray
        distance matrix generated by the ``z`` function

    Returns
    -------
    numpy.ndarray
       
    """
    return clus.fcluster(links, depth, criterion="distance")


def cluster(embedding, depth):
    """
    A clustering pipe. It requires a set of embeddings and a depth
    to return cluster numbers (needed for the hierarchical clustering cutoff)

    Parameters
    ----------
    embedding : list[list[float]]
        a list of lists of floats. It should also accept a numpy.ndarray

    depth : float
        float to signify the distance cut off point

    Returns
    -------
    numpy.ndarray
        cluster numbers for the original input
    """
    return fetch(depth, z(embedding))
